# Worker Name
name = "embeddingtest"

# Entry Point
main = "src/index.ts"

compatibility_date = "2024-03-24"

[[vectorize]]
binding = "VECTORIZE_INDEX" # available within your Worker on env.VECTORIZE_INDEX
index_name = "sjkpdk"

[ai]
binding = "AI" # available in your Worker on env.AI

[vars]
QDRANT_ENDPOINT="https://f9528bea-8de5-4729-b1d7-55d0097bdc00.us-east4-0.gcp.cloud.qdrant.io:6333"